apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentiment-logs-pvc
  labels:
    app: sentiment-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
